sudo: required

language: golang

services:
  - docker

script:
  - echo "no tests!"

after_success:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t sqspipe .
  - docker tag sqspipe:latest 723255503624.dkr.ecr.us-east-1.amazonaws.com/sqspipe:latest
  - docker push 723255503624.dkr.ecr.us-east-1.amazonaws.com/sqspipe:latest